#!/bin/sh

[ "${INTERFACE}" != "usb0" ] && exit 0

lan_ifname=$(status get lan_ifname)

addif() {
    ip link set ${INTERFACE} mtu 1500
    brctl addif ${lan_ifname} ${INTERFACE}
    sysctl -w "net.ipv6.conf.${INTERFACE}.disable_ipv6=1"
    ip link set ${INTERFACE} up
}

case "$ACTION" in
    add)
        addif
        ;;
esac
