#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org
START=23

start() {
	[ -f /etc/syslog-ng/syslog-ng.conf ] || {
		echo "/etc/syslog-ng/syslog-ng.conf does not exist !";
		exit 0;
	};

	[ -x /usr/sbin/syslog-ng ] && syslog-ng
}

stop() {
	killall syslog-ng
}

reload() {
	kill -HUP $(cat /run/syslog-ng.pid) &>/dev/null
}
