[global]
;debug avp = yes
;debug network = yes
;debug state = yes
;debug tunnel = yes
port = 1701
access control = no

[lac l2tp-IPv6]
redial = yes
redial timeout = 5
hidden bit = no 
;ppp debug = yes 
pppoptfile = /etc/ppp/options.xl2tpd
require authentication = no 
refuse authentication = no
refuse chap = no
flow bit = yes 
length bit = yes
