#!/bin/sh
RESOLVCONFTMP="/tmp/etc/resolv.conf.tmp"
RESOLVCONF="/tmp/etc/resolv.conf"
LOCK="/var/lock/update-resolv.lock"
DOMAINS=""

add_dns() {
	for dns in $@; do
	    	local new_dns=1

	    	for domain in ${DOMAINS}; do
		    	if [ ${domain} = ${dns} ]; then
			     	new_dns=0
				break
			fi
		done

		if [ "$new_dns" -eq 1 ]; then
			DOMAINS="${DOMAINS} ${dns}"
			echo nameserver ${dns} >> "${RESOLVCONFTMP}"
		fi
	done
}

lock "${LOCK}"

# this script may be called before umask is properly set:
# (0077 instead of 0022). make sure that the resolv.conf has 644 rights
echo -n > "${RESOLVCONFTMP}"
chmod 644 "${RESOLVCONFTMP}"

# dns may be updated without restarting the infra (during a dhcp-renew
# for example), so make sure that the autoconf dns is always synced
if [ "$(status get dhcpc_wan_status)" = "up" ]; then
	status set net_autoconf_dns "$(status get dhcpc_wan_dns)"
elif [ -d /etc/adsl ] && [ "$(status get dhcpc_voip_status)" = "up" ]; then
	status set net_autoconf_dns "$(status get dhcpc_voip_dns)"
elif [ -d /etc/adsl ] && [ "$(status get ppp_adsl_status)" = "up" ]; then
	status set net_autoconf_dns "$(status get ppp_adsl_dns)"
elif [ "$(status get ppp_gprs_status)" = "up" ]; then
	status set net_autoconf_dns "$(status get ppp_gprs_dns)"
else
	status set net_autoconf_dns ""
fi

add_dns $(status get net_autoconf_dns)
add_dns $(status get net_data_dns)
add_dns $(status get net_voip_dns)
add_dns $(status get net_tv_dns)
add_dns $(status get net_ipv6_dns)

mv "${RESOLVCONFTMP}" "${RESOLVCONF}"
ln -sf "${RESOLVCONF}" /etc/resolv.conf

case "$(nvram get ipv6_dns)" in
	"ipv4")
		rm -f /tmp/ipv6dns
		ln -sf /dev/null /tmp/ipv6dns
		;;
	"ipv6")
		rm -f /tmp/ipv6dns
		touch /tmp/ipv6dns
		;;
	*)
esac

lock -u "${LOCK}"
